version: "3"

services:
  web:
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    ports:
      - "8000:8000"
    command: flask run --host=0.0.0.0 --port=8000
    volumes:
      - .:/app
    networks:
      - base_network
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DB}
    volumes:
      - db_data:/data/db
    networks:
      - base_network
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGODB_URL}
    depends_on:
      - mongodb
    networks:
      - base_network

volumes:
  db_data:

networks:
  base_network:
    driver: bridge